server:
  port: 8080

spring:
  main:
    banner-mode: off
  profiles:
    active: dev
#  mvc:
#    view:
#      prefix: pages
#      suffix: .html

admin:
  name: 张三
  age: 18

logging:
  level:
    root: info
    com.yicj.study.mvc: debug

management:
  endpoints:
    web:
      exposure:
        include: info, health, hello
#        include: "*"
