server:
  port: 5555
spring:
  application:
    name: hello-gateway-swagger
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-a
          uri: lb://client-a
          predicates:
            - Path=/admin/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true